In [34]:
import pandas as pd
import numpy as np
from sklearn import preprocessing , svm 
from sklearn.linear_model import LinearRegression
import math
from sklearn.model_selection import train_test_split

In [2]:
df=pd.read_csv("D:\DATA SCIENCE BY ME\Project\Project for resume from company\stock price\AAPL.csv")
df.head()

,Date,Open,High,Low,Close,Adj Close,Volume
0,2012-09-04,95.108574,96.448570,94.928574,96.424286,87.121140,91973000
1,2012-09-05,96.510002,96.621429,95.657143,95.747147,86.509338,84093800
2,2012-09-06,96.167145,96.898575,95.828575,96.610001,87.288956,97799100
3,2012-09-07,96.864288,97.497147,96.538574,97.205711,87.827171,82416600
4,2012-09-10,97.207146,97.612854,94.585716,94.677139,85.542564,121999500

In [3]:
df=df[['Open','High','Low','Close','Volume']]

In [5]:
df['HL_PCT']=(df['High']-df['Low'])/df['Close']*100
df['HL_PCT'].head()

0    1.576362
1    1.007117
2    1.107546
3    0.986128
4    3.197327
Name: HL_PCT, dtype: float64

In [6]:
df['PCT_change']=(df['Close']-df['Open'])/df['Open']*100

In [7]:
df['PCT_change'].head()

0    1.383379
1   -0.790441
2    0.460507
3    0.352476
4   -2.602697
Name: PCT_change, dtype: float64

In [8]:
df=df[['Close','HL_PCT', 'PCT_change','Volume' ]]

In [9]:
forecast_col='Close'

In [10]:
df.isna()

      Close  HL_PCT  PCT_change  Volume
0     False   False       False   False
1     False   False       False   False
2     False   False       False   False
3     False   False       False   False
4     False   False       False   False
5     False   False       False   False
6     False   False       False   False
7     False   False       False   False
8     False   False       False   False
9     False   False       False   False
10    False   False       False   False
11    False   False       False   False
12    False   False       False   False
13    False   False       False   False
14    False   False       False   False
15    False   False       False   False
16    False   False       False   False
17    False   False       False   False
18    False   False       False   False
19    False   False       False   False
20    False   False       False   False
21    False   False       False   False
22    False   False       False   False
23    False   False       False   False
24    False   False       False   False
25    False   False       False   False
26    False   False       False   False
27    False   False       False   False
28    False   False       False   False
29    False   False       False   False
...     ...     ...         ...     ...
1228  False   False       False   False
1229  False   False       False   False
1230  False   False       False   False
1231  False   False       False   False
1232  False   False       False   False
1233  False   False       False   False
1234  False   False       False   False
1235  False   False       False   False
1236  False   False       False   False
1237  False   False       False   False
1238  False   False       False   False
1239  False   False       False   False
1240  False   False       False   False
1241  False   False       False   False
1242  False   False       False   False
1243  False   False       False   False
1244  False   False       False   False
1245  False   False       False   False
1246  False   False       False   False
1247  False   False       False   False
1248  False   False       False   False
1249  False   False       False   False
1250  False   False       False   False
1251  False   False       False   False
1252  False   False       False   False
1253  False   False       False   False
1254  False   False       False   False
1255  False   False       False   False
1256  False   False       False   False
1257  False   False       False   False

[1258 rows x 4 columns]

In [11]:
df.fillna(value=-99999 , inplace = True)

In [12]:
forecast_out = int(math.ceil(0.01*(len(df))))

In [42]:
forecast_out

13

In [14]:
len(df)

1258

In [15]:
df['label']=df[forecast_col].shift(-forecast_out)

In [16]:
df['label']

0       100.012856
1        98.684288
2        96.220001
3        95.025711
4        97.331429
5        95.300003
6        94.198570
7        94.472855
8        95.921425
9        95.257141
10       93.227142
11       91.167145
12       90.835716
13       91.558571
14       89.728569
15       89.958572
16       90.680000
17       92.827141
18       92.087143
19       90.377144
20       87.120003
21       90.575714
22       87.622856
23       88.118568
24       87.077141
25       86.285713
26       85.045715
27       85.220001
28       82.400002
29       83.517143
           ...
1228    155.320007
1229    157.479996
1230    159.850006
1231    161.600006
1232    160.949997
1233    157.860001
1234    157.500000
1235    157.210007
1236    159.779999
1237    159.979996
1238    159.270004
1239    159.860001
1240    161.470001
1241    162.910004
1242    163.350006
1243    164.000000
1244    164.050003
1245           NaN
1246           NaN
1247           NaN
1248           NaN
1249           NaN
1250           NaN
1251           NaN
1252           NaN
1253           NaN
1254           NaN
1255           NaN
1256           NaN
1257           NaN
Name: label, Length: 1258, dtype: float64

In [17]:
df.dropna(inplace=True)

In [18]:
df

           Close    HL_PCT  PCT_change     Volume       label
0      96.424286  1.576362    1.383379   91973000  100.012856
1      95.747147  1.007117   -0.790441   84093800   98.684288
2      96.610001  1.107546    0.460507   97799100   96.220001
3      97.205711  0.986128    0.352476   82416600   95.025711
4      94.677139  3.197327   -2.602697  121999500   97.331429
5      94.370003  2.058764   -0.679587  125995800   95.300003
6      95.684288  2.075273    0.440885  178058300   94.198570
7      97.568573  1.571059    0.828205  149590000   94.472855
8      98.754288  1.314957    0.191320  150118500   95.921425
9      99.968575  0.741658    0.061489   99507800   95.257141
10    100.272858  0.841987    0.290051   93375800   93.227142
11    100.300003  0.629543    0.262765   81718700   91.167145
12     99.814285  0.921710   -0.065791   84142100   90.835716
13    100.012856  0.815615   -0.330291  142897300   91.558571
14     98.684288  1.754514    0.572173  159941600   89.728569
15     96.220001  2.936723   -2.138729  129697400   89.958572
16     95.025711  1.727349   -0.532348  144125800   90.680000
17     97.331429  3.202606    2.563636  148522500   92.827141
18     95.300003  2.152602   -1.716389  133777700   92.087143
19     94.198570  3.071024   -1.753679  135898700   90.377144
20     94.472855  2.374078   -0.075556  156998100   87.120003
21     95.921425  1.374639    0.991179  106070300   90.575714
22     95.257141  1.304733   -0.662947   92681400   87.622856
23     93.227142  2.255630   -1.895672  148501500   88.118568
24     91.167145  1.794190   -1.346462  159498500   87.077141
25     90.835716  2.664148   -0.438427  209649300   86.285713
26     91.558571  1.245104    0.182889  127589000   85.045715
27     89.728569  3.040923   -2.846094  136520300   85.220001
28     89.958572  1.600731    0.023829  115003700   82.400002
29     90.680000  1.777049    0.381116  108125500   83.517143
...          ...       ...         ...        ...         ...
1215  144.089996  1.436597    0.278373   21569600  152.089996
1216  142.729996  0.763677   -0.202774   24128800  152.740005
1217  144.179993  1.283123    0.895731   19201700  153.460007
1218  145.059998  1.778576    0.659217   21090600  150.559998
1219  145.529999  1.010102    0.552755   19781800  149.500000
1220  145.740005  0.933159   -0.089114   24884500  148.729996
1221  147.770004  2.064020    1.560140   25199400  150.050003
1222  149.039993  1.341922    0.723114   20132100  157.139999
1223  149.559998  1.557895    0.497239   23793500  155.570007
1224  150.080002  0.972819    0.589816   17868800  156.389999
1225  151.020004  0.973382    0.358857   20923000  158.809998
1226  150.339996  1.030998   -0.765679   17243700  160.080002
1227  150.270004  1.038129    0.186678   26252600  161.059998
1228  152.089996  1.670069    1.002785   21493200  155.320007
1229  152.740005  1.335598    0.619237   18853900  157.479996
1230  153.460007  0.566920    0.071732   15781000  159.850006
1231  150.559998  4.443413   -2.074798   32476300  161.600006
1232  149.500000  0.695648   -0.260190   17213700  160.949997
1233  148.729996  1.479189   -0.780519   19845900  157.860001
1234  150.050003  1.206263    0.637154   35368600  157.500000
1235  157.139999  2.284584   -1.343546   69936800  157.210007
1236  155.570007  1.407728   -0.942372   27097300  159.779999
1237  156.389999  1.093415    0.205031   20559900  159.979996
1238  158.809998  1.416787    1.114224   21870300  159.270004
1239  160.080002  2.223887    0.933163   36205900  159.860001
1240  161.059998  1.341117    1.130229   26131500  161.470001
1241  155.320007  3.457375   -2.864282   40804300  162.910004
1242  157.479996  1.587503    0.561935   26257100  163.350006
1243  159.850006  0.913361    0.332663   22028200  164.000000
1244  161.600006  1.274751    0.585088   29465500  164.050003

[1245 rows x 5 columns]

In [28]:
X= np.array(df.drop(['label'],1))
y=np.array(df['label'])

In [29]:
y

array([100.012856,  98.684288,  96.220001, ..., 163.350006, 164.      ,
       164.050003])

In [32]:
X=preprocessing.scale(X)

In [35]:
X_train , X_test , y_train, y_test= train_test_split(X, y , test_size=0.2)

In [38]:
clf=LinearRegression()
clf.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [40]:
accuracy=clf.score(X_test , y_test)

In [41]:
accuracy

0.9577463888256432